# Generated by Django 4.2 on 2023-04-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='watermraked_image',
            field=models.ImageField(null=True, upload_to='output/'),
        ),
    ]
